image: Visual Studio 2019

platform:
- x86
- x64

configuration:
  - Debug
  - Release
  
environment:
  matrix:
  - SHARED: OFF
    POSTFIXNAME: MT
  - SHARED: ON
    POSTFIXNAME: MD
    
matrix:
  fast_finish: true
  
install:
  - mkdir build
  - cd build

build_script:  
  - echo Visual Studio 16 2019 %SHARED% %configuration%
  - cmake .. -G"Visual Studio 16 2019" -DBUILD_SHARED_LIBS=%SHARED% -DARCHITECTURE=%platform% -DCMAKE_INSTALL_PREFIX=./output
  - cmake --build . --target INSTALL --config %configuration%
  - 7z a vc140_%configuration%_%PLATFORM%_%POSTFIXNAME%.zip  -i!%APPVEYOR_BUILD_FOLDER%\build\output\*
  - appveyor PushArtifact vc140_%configuration%_%PLATFORM%_%POSTFIXNAME%.zip
  
deploy:
  provider: GitHub
  auth_token:
    secure: WCGi6SXwa6VaPyLH6fZCrmTix+e2FA3zwzhNg8dSf3EdrcecGIR3Z0qG/vssOdfA 
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true 
