dist: focal 
language : cpp

matrix:
  include:
    - os: osx
      osx_image: xcode12.2
      compiler: clang
    - os: linux 
      env: BUILD_TYPE=Release
      addons:
        apt:
          packages:
            - libx11-dev
            - libxfixes-dev 
            - libxtst-dev
            - libxinerama-dev
            - cmake
before_install:
  - if [[ "$CXX" == "g++" ]]; then export CC="gcc-9"                                                                    ;fi
  - if [[ "$CXX" == "g++" ]]; then export CXX="g++-9"                                                                   ;fi

script:
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_SHARED_LIBS=OFF -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_C_COMPILER="$CC" . && make;
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_SHARED_LIBS=ON -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_C_COMPILER="$CC" . && make;
    
notifications:
  email: false
