language : cpp
    
matrix:
  include:
    - os: osx
      osx_image: xcode12.2
      compiler: clang
    - os: linux
      env: BUILD_TYPE=Release
      addons: 
        apt:
          packages:
            - libx11-dev
            - libxfixes-dev 
            - libxtst-dev
            - libxinerama-dev
          sources: 
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
      
before_install:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.2-Linux-x86_64.tar.gz"
      mkdir -p ${TRAVIS_BUILD_DIR}/deps/cmake && travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C ${TRAVIS_BUILD_DIR}/deps/cmake
      export PATH="${TRAVIS_BUILD_DIR}/deps/cmake/bin:${PATH}";
    else
      brew update && brew upgrade cmake || brew install cmake;
    fi
  
script:
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_SHARED_LIBS=OFF . && make;
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_SHARED_LIBS=ON . && make;
    
notifications:
  email: false
