language : cpp
    
matrix:
  include:
    - os: osx
      osx_image: xcode12.2
      compiler: clang
    - os: linux 
      env: CLANG_VERSION=12.0 BUILD_TYPE=Release
      addons: &clang12
        apt:
          packages:
            - clang-12
            - libx11-dev
            - libxfixes-dev 
            - libxtst-dev
            - libxinerama-dev
            - cmake
          sources: 
            - ubuntu-toolchain-r-test
before_install:
  - if [[ -n "$CLANG_VERSION" ]]; then export CXX=clang++-$CLANG_VERSION CC=clang-$CLANG_VERSION; fi

script:
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_SHARED_LIBS=OFF -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_C_COMPILER="$CC" . && make;
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_SHARED_LIBS=ON -DCMAKE_CXX_COMPILER="$CXX" -DCMAKE_C_COMPILER="$CC" . && make;
    
notifications:
  email: false
