language : cpp
    
matrix:
  include:
    - os: osx
      osx_image: xcode12.2
      compiler: clang
    - os: linux
      env: BUILD_TYPE=Release
      addons: 
        apt:
          packages:
            - libx11-dev
            - libxfixes-dev 
            - libxtst-dev
            - libxinerama-dev
            - cmake
          sources: 
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise
script:
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_SHARED_LIBS=OFF . && make;
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_SHARED_LIBS=ON . && make;
    
notifications:
  email: false
