parameters:
    - name: name
    - name: targetPlatform
    - name: image

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.image }} 
    steps: 
      - task: run-cmake@0
        inputs:
          cmakeArgs: '.. -G"Visual Studio 16 2019" -A ${{ parameters.targetPlatform }} -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./output'