parameters:
    - name: name
    - name: targetPlatform
    - name: image

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.image }} 
    steps: 
      - task: CMake@1
        inputs:
          cmakeArgs: '.. -G"Visual Studio 16 2019" -A ${{ parameters.targetPlatform }} -DCMAKE_INSTALL_PREFIX=./output'
      - task: CMake@1
        inputs:
          cmakeArgs: '--build . --target INSTALL'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.SourcesDirectory)/build/output'
          ArtifactName: 'drop'
          publishLocation: 'Container'