parameters:
    - name: name
    - name: targetPlatform
    - name: image

jobs:
  - job: ${{ parameters.name }}
    pool:
      vmImage: ${{ parameters.image }} 
    steps: 
      - task: CMake@1
        inputs:
          cmakeArgs: '.. -G"Visual Studio 16 2019" -A ${{ parameters.targetPlatform }} -DCMAKE_INSTALL_PREFIX=./output'
      - task: CMake@1
        inputs:
          cmakeArgs: '--build . --target INSTALL'
      - task: GitHubRelease@1
        inputs:
          gitHubConnection: 'smasherprog'
          repositoryName: 'smasherprog/screen_capture_lite'
          action: 'create'
          target: '$(Build.SourceVersion)' 
          assets: '$(Build.SourcesDirectory)/build/output/*'
          tagSource: 'gitTag'
          releaseNotesFilePath: 'releasenotes.txt'
          changeLogCompareToRelease: 'lastFullRelease'
          changeLogType: 'commitBased'